packages:
  - apps/*
  - packages/*

catalog:
  "@sveltejs/adapter-vercel": ^6.2.0
  "@sveltejs/kit": ^2.22.2
  "@sveltejs/vite-plugin-svelte": ^6.2.1
  "@tailwindcss/postcss": ^4.1.11
  daisyui: 5.0.43
  eslint: ^9.20.1
  eslint-config-prettier: ^10.0.1
  eslint-plugin-svelte: ^3.13.1
  postcss: ^8.5.6
  prettier: ^3.5.1
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.7.2
  svelte: ^5.34.9
  svelte-check: ^4.1.4
  tailwindcss: ^4.1.10
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
  vite: ^7.2.7
  axios: ^1.9.0
  lucide-svelte: ^0.561.0
  luxon: ^3.6.1
  ts-pattern: ^5.7.1
