name: Deploy

inputs:
  # SSH
  host:
    required: true
  username:
    required: true
  port:
    required: true
  ssh-private-key:
    required: true

  # Docker
  image-name:
    required: true
  server-port:
    required: true
  container-name:
    required: true
  application-port:
    required: true
  api-base-url:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Update image inside VPS
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
      with:
        host: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        KEY: ${{ inputs.ssh-private-key }}
        script: |
          docker pull ${{ inputs.image-name }}
          docker rm -f ${{ inputs.container-name }}
          docker run -d \
          -p ${{ inputs.server-port }}:${{ inputs.application-port }} \
          --restart=always \
          --name ${{ inputs.container-name }} \
          -e VITE_API_BASE_URL=${{ inputs.api-base-url }} \
          ${{ inputs.image-name }}
