/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/status_pages/{statusPageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a public status page */
        get: operations["readStatusPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        StatusPageStatus: "operational" | "degraded" | "outage" | "unknown";
        /** @enum {string} */
        StatusPageMonitorStatus: "up" | "degraded" | "down" | "unknown";
        StatusPageUptimeDto: {
            /** @description Percent, null without checks */
            "1h": number | null;
            /** @description Percent, null without checks */
            "24h": number | null;
            /** @description Percent, null without checks */
            "7d": number | null;
            /** @description Percent, null without checks */
            "30d": number | null;
            /** @description Percent, null without checks */
            "90d": number | null;
        };
        StatusPageBucketDto: {
            /**
             * Format: date-time
             * @description Start of the UTC day
             */
            timestamp: string;
            successCount: number;
            failureCount: number;
            /** @description Null when the day has no checks */
            averageLatencyMs: number | null;
        };
        StatusPageHistoryDto: {
            /** @description 90 UTC days, oldest first, today last. Days without checks have zero counts. */
            daily: components["schemas"]["StatusPageBucketDto"][];
        };
        StatusPagePingDto: {
            /** Format: date-time */
            createdAt: string;
            /** @description 0 when the request got no response */
            statusCode: number;
            responseTimeMs: number;
        };
        StatusPageMonitorDto: {
            /** @description Stable public key of the monitor */
            id: string;
            name: string;
            status: components["schemas"]["StatusPageMonitorStatus"];
            uptime: components["schemas"]["StatusPageUptimeDto"];
            history: components["schemas"]["StatusPageHistoryDto"];
            /** @description Last 100 checks, oldest first */
            pings: components["schemas"]["StatusPagePingDto"][];
        };
        StatusPageDto: {
            name: string;
            status: components["schemas"]["StatusPageStatus"];
            /**
             * Format: date-time
             * @description When the server composed this response
             */
            updatedAt: string;
            /** @description In the order configured on the status page */
            monitors: components["schemas"]["StatusPageMonitorDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Status page id or its verified custom domain */
                statusPageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPageDto"];
                };
            };
            /** @description The status page is not public */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No status page with this id or domain */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
