name: Deploy

inputs:
  # SSH
  host:
    required: true
  username:
    required: true
  port:
    required: true
  ssh-private-key:
    required: true

  # Docker
  image-name:
    required: true
  server-port:
    required: true
  container-name:
    required: true
  application-port:
    required: true

  # App
  mongo-url:
    required: true
  github-oauth-client-id:
    required: true
  github-oauth-client-secret:
    required: true
  resend-api-key:
    required: true
  resend-audience-enabled:
    required: false
  stripe-api-key-secret:
    required: false
  stripe-signature:
    required: false
  our-env:
    required: true
  redis-url:
    required: true
  stripe-early-bird-price-id:
    required: false
  demo-dashboard-api-key:
    required: false
  logdash-api-key:
    required: false
  telegram-token:
    required: false
  whitelisted-emails:
    required: false
  auth-jwt-secret:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Update image inside VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        KEY: ${{ inputs.ssh-private-key }}
        script: |
          docker pull ${{ inputs.image-name }}
          docker rm -f ${{ inputs.container-name }}
          docker run -d \
          -p ${{ inputs.server-port }}:${{ inputs.application-port }} \
          --restart=always \
          --add-host=host.docker.internal:host-gateway \
          --name ${{ inputs.container-name }} \
          -e MONGO_URL=${{ inputs.mongo-url }} \
          -e GITHUB_OAUTH_CLIENT_ID=${{ inputs.github-oauth-client-id }} \
          -e GITHUB_OAUTH_CLIENT_SECRET=${{ inputs.github-oauth-client-secret }} \
          -e RESEND_API_KEY=${{ inputs.resend-api-key }} \
          -e STRIPE_API_KEY_SECRET=${{ inputs.stripe-api-key-secret }} \
          -e STRIPE_SIGNATURE=${{ inputs.stripe-signature }} \
          -e OUR_ENV=${{ inputs.our-env }} \
          -e REDIS_URL=${{ inputs.redis-url }} \
          -e STRIPE_EARLY_BIRD_PRICE_ID=${{ inputs.stripe-early-bird-price-id }} \
          -e DEMO_DASHBOARD_API_KEY=${{ inputs.demo-dashboard-api-key }} \
          -e LOGDASH_API_KEY=${{ inputs.logdash-api-key }} \
          -e TELEGRAM_TOKEN=${{ inputs.telegram-token }} \
          -e WHITELISTED_EMAILS=${{ inputs.whitelisted-emails }} \
          -e AUTH_JWT_SECRET=${{ inputs.auth-jwt-secret }} \
          ${{ inputs.image-name }}
