import { UserTier } from '$lib/domains/shared/types.js';

export const PAYMENT_PLANS = [
  {
    name: 'Hobby',
    price: 'Free forever',
    description:
      'Great for kicking the tires or for your personal stuff. No credit card required.',
    features: [
      { name: 'Unlimited projects' },
      { name: 'Up to 5 services' },
      { name: 'Up to 5 http monitors' },
      { name: 'Up to 1 public dashboards' },
      { name: 'Up to 5 metrics per service' },
      { name: 'Up to 1 extra user per project' },
      { name: 'Monitoring channels (Telegram & Basic Webhooks)' },
      { name: '24 hours logs retention (240k logs per service)' },
      { name: '24 hours metrics retention' },
      { name: 'Quick insights with short-term data granularity' },
      { name: 'Feature requests' },
      { name: 'Vibrant Discord community' },
    ],
    badge: {
      text: 'No credit card required',
      class: 'badge-secondary',
    },
    buttonText: 'Select Hobby',
    guarantee: 'No commitment required',
    tier: UserTier.FREE,
    popular: false,
  },
  {
    name: 'Builder',
    price: '$9/mo.',
    period: 'per month',
    description:
      'Ideal for teams and projects that need more features and support.',
    features: [
      { name: 'Everything in Hobby, plus:' },
      { name: 'Up to 20 services' },
      { name: 'Up to 20 http monitors' },
      { name: 'Up to 5 public dashboards' },
      { name: 'Up to 10 metrics per service' },
      { name: 'Up to 2 extra users per project' },
      { name: 'Monitoring channels (Telegram & Advanced Webhooks & Email)' },
      { name: '7 days logs retention (4.2M logs per service)' },
      { name: '7 days metrics retention' },
      { name: 'Comprehensive insights with extended data granularity' },
      { name: 'Priority support' },
      { name: 'Dedicated Discord channel with us' },
      { name: 'Regular catch-up calls' },
      { name: 'Early access to new features' },
      { name: 'Priority feature requests' },
    ],
    badge: {
      text: 'Save 10%',
      class: 'badge-primary',
    },
    buttonText: 'Start free trial',
    guarantee: '30-day money-back guarantee',
    tier: UserTier.BUILDER,
    popular: true,
  },
  {
    name: 'Pro',
    price: '$29/mo.',
    period: 'per month',
    description:
      'Perfect for small teams and startups. Get more projects, metrics, and support.',
    features: [
      { name: 'Everything in Builder, plus:' },
      { name: 'Up to 50 services' },
      { name: 'Up to 50 http monitors' },
      { name: 'Up to 15 public dashboards' },
      { name: 'Up to 30 metrics per service' },
      { name: 'Up to 3 extra users per project' },
      {
        name: 'Monitoring channels (Telegram & Advanced Webhooks & Email & SMS)',
      },
      { name: '30 days logs retention (37M logs per service)' },
      { name: '30 days metrics retention' },
      { name: '99.9% uptime SLA' },
      { name: 'Advanced insights with detailed data granularity' },
      { name: 'Team management features' },
      { name: 'Custom branding options' },
      { name: 'Custom status page domain' },
    ],
    badge: {
      text: 'Getting serious',
      class: 'badge-secondary',
    },
    buttonText: 'Start free trial',
    guarantee: '30-day money-back guarantee',
    tier: UserTier.PRO,
    popular: false,
    disabled: false,
  },
] as const;
