import type { UserTier } from '$lib/domains/shared/types.js';

export type OAuthProvider = 'github' | 'google';

/**
 * The provider url (and the csrf `state` bound to it) is generated by the bff so
 * that the callback can verify the round trip against an httpOnly cookie.
 */
export const startOAuthLogin = async (dto: {
  provider: OAuthProvider;
  terms_accepted: boolean;
  email_accepted: boolean;
  tier?: UserTier | null;
  next_url?: string;
}): Promise<void> => {
  const response = await fetch('/app/api/auth/oauth-start', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(dto),
  });

  if (!response.ok) {
    throw new Error(`Could not start ${dto.provider} login`);
  }

  const { url } = (await response.json()) as { url: string };

  window.location.href = url;
};
