import type { OAuthProvider } from '$lib/domains/auth/domain/oauth-provider';
import { requestOAuthUrl } from '$lib/domains/auth/infrastructure/request-oauth-url';
import type { UserTier } from '$lib/domains/shared/types.js';

/**
 * The provider url (and the csrf `state` bound to it) is generated by the bff so
 * that the callback can verify the round trip against an httpOnly cookie.
 */
export const startOAuthLogin = async (dto: {
  provider: OAuthProvider;
  next_url?: string;
  flow?: 'login' | 'claim';
  tier?: UserTier;
}): Promise<void> => {
  window.location.href = await requestOAuthUrl(dto);
};
