name: 'Apply clickhouse migrations'

inputs:
  host:
    required: true
  user:
    required: true
  password:
    required: true
  db:
    required: true
  migrations-home:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install clickhouse-migrations globally
      run: npm install -g clickhouse-migrations
      shell: bash

    - name: Run ClickHouse migrations
      run: |
        npx clickhouse-migrations migrate \
          --host="${{ inputs.host }}" \
          --user="${{ inputs.user }}" \
          --password="${{ inputs.password }}" \
          --db="${{ inputs.db }}" \
          --migrations-home="${{ inputs.migrations-home }}"
      shell: bash
