import { UserTier } from './types.js';

export const PAYMENT_PLANS = [
  {
    name: 'Hobby',
    price: 'Free',
    description:
      'Great for kicking the tires or for your personal stuff. No credit card required.',
    features: [
      { name: 'Unlimited projects' },
      { name: 'Up to 5 services' },
      { name: 'Up to 5 http monitors' },
      { name: 'Up to 1 public dashboards' },
      { name: 'Up to 5 metrics per service' },
      { name: 'Monitoring channels (Telegram & Webhooks)' },
      { name: 'Access 1,000 most recent logs' },
      { name: '1 week metrics retention' },
      { name: 'Quick insights with short-term data granularity' },
      { name: 'Feature requests' },
      { name: 'Vibrant Discord community' },
    ],
    badge: {
      text: 'No credit card required',
      class: 'badge-secondary',
    },
    buttonText: 'Select Hobby',
    guarantee: 'No commitment required',
    tier: UserTier.FREE,
    popular: false,
  },
  {
    name: 'Early Bird',
    price: '$3/mo.',
    period: 'per month',
    description:
      'Ideal for Logdash believers and early adopters. Get extra personal touch and support.',
    features: [
      { name: 'Everything in Hobby, plus:' },
      { name: 'Up to 20 services' },
      { name: 'Up to 20 http monitors' },
      { name: 'Up to 5 public dashboards' },
      { name: 'Up to 10 metrics per service' },
      { name: 'Monitoring channels (Telegram & Webhooks & Email)' },
      { name: 'Lifetime access to 10,000 most recent logs' },
      { name: '1 month metrics retention' },
      { name: 'Comprehensive insights with extended data granularity' },
      { name: 'Priority support' },
      { name: 'Dedicated Discord channel with us' },
      { name: 'Regular catch-up calls' },
      { name: 'Early access to new features' },
      { name: 'Priority feature requests' },
    ],
    badge: {
      text: 'Save 50%, 4 spots left',
      class: 'badge-primary',
    },
    buttonText: 'Select Early Bird',
    guarantee: '30-day money-back guarantee',
    tier: UserTier.EARLY_BIRD,
    popular: true,
  },
  {
    name: 'Pro',
    price: '$9/mo.',
    period: 'per month',
    description:
      'Perfect for small teams and startups. Get more projects, metrics, and support.',
    features: [
      { name: 'Everything in Early Bird, plus:' },
      { name: 'Up to 50 services' },
      { name: 'Up to 50 http monitors' },
      { name: 'Up to 25 public dashboards' },
      { name: 'Up to 30 metrics per service' },
      { name: 'Monitoring channels (Telegram & Webhooks & Email & SMS)' },
      { name: 'Lifetime access to 50,000 most recent logs' },
      { name: '3 months metrics retention' },
      { name: '99.9% uptime SLA' },
      { name: 'Advanced insights with detailed data granularity' },
      { name: 'Team management features' },
      { name: 'Custom branding options' },
      { name: 'Custom status page domain' },
    ],
    badge: {
      text: 'Coming soon',
      class: 'badge-secondary',
    },
    buttonText: 'Coming soon',
    guarantee: '30-day money-back guarantee',
    tier: UserTier.PRO,
    popular: false,
    disabled: true,
  },
] as const;
