type LookupChannel = 'Email' | 'AI assistants' | 'Organic search' | 'Organic social' | 'Referral';

type Lookup = Partial<Record<LookupChannel, string[]>>;

const LOOKUP_CHANNELS: LookupChannel[] = [
  'Email',
  'AI assistants',
  'Organic search',
  'Organic social',
  'Referral',
];

const PAID_MEDIUMS = [
  'cpc',
  'cpm',
  'cpv',
  'cpa',
  'cpp',
  'ppc',
  'sem',
  'retargeting',
  'remarketing',
  'display',
  'banner',
  'ad',
  'ads',
  'advertising',
  'sponsored',
];

const PAID_CLICK_IDS = ['gclid', 'gbraid', 'wbraid', 'gad_source', 'dclid', 'msclkid'];

const SOCIAL_CLICK_IDS = ['fbclid', 'ttclid', 'twclid', 'li_fat_id'];

const SOURCES_AND_HOSTS: Lookup = {
  Email: [
    'email',
    'e-mail',
    'mail',
    'newsletter',
    'gmail',
    'outlook',
    'mailchimp',
    'klaviyo',
    'sendgrid',
    'brevo',
    'sendinblue',
    'convertkit',
    'beehiiv',
    'buttondown',
    'mailerlite',
    'mail.google.com',
    'inbox.google.com',
    'com.google.android.gm',
    'outlook.live.com',
    'outlook.office.com',
    'outlook.office365.com',
    'outlook.cloud.microsoft',
    'outlook.com',
    'mail.yahoo.com',
    'mail.yahoo.co.jp',
    'mail.aol.com',
    'mail.proton.me',
    'mail.protonmail.com',
    'fastmail.com',
    'hey.com',
    'mail.com',
    'mail.zoho.com',
    'mail.zoho.eu',
    'mail.zoho.in',
    'app.tuta.com',
    'mail.tutanota.com',
    'mail.superhuman.com',
    'mail.yandex.ru',
    'mail.yandex.com',
    'e.mail.ru',
    'mail.rambler.ru',
    'mail.qq.com',
    'wx.mail.qq.com',
    'exmail.qq.com',
    'mail.163.com',
    'mail.126.com',
    'mail.naver.com',
    'mail.daum.net',
    'email.seznam.cz',
    'gmx.net',
    'gmx.de',
    'gmx.com',
    'web.de',
    'email.t-online.de',
    'mail.libero.it',
    'poczta.onet.pl',
    'poczta.wp.pl',
    'poczta.interia.pl',
    'poczta.o2.pl',
  ],
  'AI assistants': [
    'chatgpt',
    'openai',
    'perplexity',
    'claude',
    'gemini',
    'copilot',
    'deepseek',
    'grok',
    'mistral',
    'phind',
    'chatgpt.com',
    'chat.openai.com',
    'perplexity.ai',
    'claude.ai',
    'gemini.google.com',
    'bard.google.com',
    'aistudio.google.com',
    'notebooklm.google.com',
    'copilot.microsoft.com',
    'copilot.cloud.microsoft',
    'edgeservices.bing.com',
    'chat.mistral.ai',
    'chat.deepseek.com',
    'grok.com',
    'meta.ai',
    'you.com',
    'phind.com',
    'poe.com',
    'character.ai',
    'pi.ai',
    'duck.ai',
    'felo.ai',
    'iask.ai',
    'lmarena.ai',
    'kimi.com',
    'kimi.moonshot.cn',
    'chat.qwen.ai',
    'tongyi.aliyun.com',
    'yiyan.baidu.com',
    'doubao.com',
    'chatglm.cn',
    'z.ai',
  ],
  'Organic search': [
    'google',
    'bing',
    'yahoo',
    'yandex',
    'baidu',
    'duckduckgo',
    'ecosia',
    'startpage',
    'qwant',
    'kagi',
    'naver',
    'seznam',
    'sogou',
    'google.com',
    'com.google.android.googlequicksearchbox',
    'bing.com',
    'yahoo.com',
    'yahoo.co.jp',
    'yandex.ru',
    'yandex.com',
    'ya.ru',
    'go.mail.ru',
    'baidu.com',
    'duckduckgo.com',
    'ecosia.org',
    'startpage.com',
    'qwant.com',
    'kagi.com',
    'search.brave.com',
    'naver.com',
    'daum.net',
    'seznam.cz',
    'sogou.com',
    'so.com',
    'sm.cn',
    'ask.com',
    'search.aol.com',
    'mojeek.com',
    'metager.org',
    'metager.de',
    'swisscows.com',
    'yep.com',
    'presearch.com',
    'lilo.org',
    'coccoc.com',
    'petalsearch.com',
    'search.goo.ne.jp',
    'info.com',
    'dogpile.com',
    'webcrawler.com',
  ],
  'Organic social': [
    'facebook',
    'fb',
    'meta',
    'instagram',
    'ig',
    'messenger',
    'whatsapp',
    'threads',
    'x',
    'twitter',
    'linkedin',
    'reddit',
    'hn',
    'hackernews',
    'youtube',
    'yt',
    'tiktok',
    'vimeo',
    'twitch',
    'pinterest',
    'tumblr',
    'snapchat',
    'discord',
    'telegram',
    'slack',
    'bluesky',
    'bsky',
    'mastodon',
    'quora',
    'medium',
    'producthunt',
    'indiehackers',
    'vk',
    'weibo',
    'wechat',
    'line',
    'facebook.com',
    'fb.com',
    'fb.me',
    'fb.watch',
    'messenger.com',
    'm.me',
    'instagram.com',
    'threads.net',
    'threads.com',
    'whatsapp.com',
    'wa.me',
    'x.com',
    'twitter.com',
    't.co',
    'linkedin.com',
    'lnkd.in',
    'reddit.com',
    'redd.it',
    'news.ycombinator.com',
    'hn.algolia.com',
    'lobste.rs',
    'slashdot.org',
    'youtube.com',
    'youtu.be',
    'tiktok.com',
    'vimeo.com',
    'twitch.tv',
    'kick.com',
    'dailymotion.com',
    'rumble.com',
    'pinterest.com',
    'pin.it',
    'tumblr.com',
    'snapchat.com',
    'discord.com',
    'discord.gg',
    'discordapp.com',
    't.me',
    'telegram.me',
    'telegram.org',
    'slack.com',
    'teams.microsoft.com',
    'teams.live.com',
    'bsky.app',
    'mastodon.social',
    'mastodon.online',
    'mstdn.social',
    'mas.to',
    'fosstodon.org',
    'hachyderm.io',
    'infosec.exchange',
    'lemmy.world',
    'tildes.net',
    'warpcast.com',
    'truthsocial.com',
    'quora.com',
    'medium.com',
    'dev.to',
    'producthunt.com',
    'indiehackers.com',
    'stackoverflow.com',
    'stackexchange.com',
    'superuser.com',
    'serverfault.com',
    'askubuntu.com',
    'steamcommunity.com',
    'soundcloud.com',
    'flickr.com',
    'deviantart.com',
    'behance.net',
    'dribbble.com',
    'xing.com',
    'nextdoor.com',
    'meetup.com',
    'vk.com',
    'ok.ru',
    'weibo.com',
    'weibo.cn',
    'douyin.com',
    'bilibili.com',
    'b23.tv',
    'zhihu.com',
    'xiaohongshu.com',
    'douban.com',
    'tieba.baidu.com',
    'weixin.qq.com',
    'mp.weixin.qq.com',
    'line.me',
    'band.us',
    'blog.naver.com',
    'cafe.naver.com',
    'cafe.daum.net',
    'note.com',
    'ameblo.jp',
    'mixi.jp',
    'nicovideo.jp',
    'dcard.tw',
    'ptt.cc',
    'plurk.com',
    'com.facebook.katana',
    'com.facebook.lite',
    'com.facebook.orca',
    'com.instagram.android',
    'com.instagram.barcelona',
    'com.whatsapp',
    'com.twitter.android',
    'com.linkedin.android',
    'com.reddit.frontpage',
    'com.google.android.youtube',
    'com.zhiliaoapp.musically',
    'com.ss.android.ugc.trill',
    'com.pinterest',
    'com.snapchat.android',
    'com.discord',
    'com.slack',
    'org.telegram.messenger',
    'jp.naver.line.android',
    'com.tencent.mm',
    'com.vkontakte.android',
  ],
  Referral: [
    'accounts.google.com',
    'myaccount.google.com',
    'docs.google.com',
    'drive.google.com',
    'sites.google.com',
    'groups.google.com',
    'calendar.google.com',
    'meet.google.com',
    'play.google.com',
    'support.google.com',
    'developers.google.com',
    'cloud.google.com',
    'console.cloud.google.com',
    'analytics.google.com',
    'ads.google.com',
    'search.google.com',
  ],
};

const MEDIUMS: Lookup = {
  Email: ['email', 'e-mail', 'e_mail', 'mail', 'newsletter'],
  'Organic social': [
    'social',
    'social-network',
    'social_network',
    'social-media',
    'social_media',
    'socialmedia',
    'sm',
  ],
  'Organic search': ['organic'],
  Referral: ['referral'],
};

const MULTI_TLD_BRANDS: Lookup = {
  'Organic search': [
    'google',
    'bing',
    'yahoo',
    'yandex',
    'baidu',
    'duckduckgo',
    'ecosia',
    'startpage',
    'qwant',
    'seznam',
  ],
  'Organic social': ['pinterest'],
};

function checked(key: string): string {
  if (!/^[a-z0-9._-]+$/.test(key)) throw new Error(`Invalid web analytics channel key: ${key}`);
  return key;
}

function list(keys: string[]): string {
  return keys.map((key) => `'${checked(key)}'`).join(', ');
}

function keyed(table: Lookup, prefix: string): [string, number][] {
  return LOOKUP_CHANNELS.flatMap((channel, index) =>
    (table[channel] ?? []).map((key): [string, number] => [`${prefix}${checked(key)}`, index + 1]),
  );
}

function lookupTable(): string {
  const entries = [
    ...keyed(SOURCES_AND_HOSTS, ''),
    ...keyed(MEDIUMS, 'medium:'),
    ...keyed(MULTI_TLD_BRANDS, 'brand:'),
  ];
  const duplicate = entries.find(([key], index) => entries.findIndex(([k]) => k === key) !== index);
  if (duplicate) throw new Error(`Duplicate web analytics channel key: ${duplicate[0]}`);
  return `[${entries.map(([key]) => `'${key}'`).join(', ')}], [${entries.map(([, index]) => index).join(', ')}]`;
}

export const WEB_ANALYTICS_CHANNEL = `multiIf(
  lower(utm_medium) IN (${list(PAID_MEDIUMS)}) OR startsWith(lower(utm_medium), 'paid') OR click_id IN (${list(PAID_CLICK_IDS)}), 'Paid',
  referrer = '' AND utm_source = '' AND utm_medium = '' AND click_id = '', 'Direct',
  transform(
    arrayFirst(found -> found > 0, arrayMap(key -> transform(key, ${lookupTable()}, 0), [
      lower(utm_source),
      concat('medium:', lower(utm_medium)),
      referrer,
      cutToFirstSignificantSubdomain(referrer),
      concat('brand:', firstSignificantSubdomain(referrer))
    ])),
    [${LOOKUP_CHANNELS.map((_, index) => index + 1).join(', ')}],
    [${LOOKUP_CHANNELS.map((channel) => `'${channel}'`).join(', ')}],
    multiIf(
      click_id IN (${list(SOCIAL_CLICK_IDS)}), 'Organic social',
      referrer != '', 'Referral',
      utm_source != '', 'Campaign',
      'Direct'
    )
  )
)`;
