name: Deploy backend (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - never
    paths:
      - 'apps/backend/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: './.github/templates/test'

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          context: ./apps/backend
          file: ./Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/logdash-backend-prod
      - name: Deploy
        uses: './.github/templates/deploy-container'
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
          server-port: 80
          application-port: 3000
          image-name: ablaszkiewicz/logdash-backend-prod
          container-name: logdash-backend-prod
          mongo-url: ${{ secrets.BACKEND_PROD_MONGO_URL }}
          github-oauth-client-id: ${{ secrets.BACKEND_PROD_GITHUB_OAUTH_CLIENT_ID }}
          github-oauth-client-secret: ${{ secrets.BACKEND_PROD_GITHUB_OAUTH_CLIENT_SECRET }}
          resend-api-key: ${{ secrets.BACKEND_PROD_RESEND_API_KEY }}
          resend-audience-enabled: 'true'
          stripe-api-key-secret: ${{ secrets.BACKEND_PROD_STRIPE_API_KEY_SECRET }}
          stripe-signature: ${{ secrets.BACKEND_PROD_STRIPE_SIGNATURE }}
          our-env: prod
          redis-url: ${{ secrets.BACKEND_PROD_REDIS_URL }}
          stripe-early-bird-price-id: ${{ secrets.BACKEND_PROD_STRIPE_EARLY_BIRD_PRICE_ID }}
          demo-dashboard-api-key: ${{ secrets.BACKEND_PROD_DEMO_DASHBOARD_API_KEY }}
          logdash-api-key: ${{ secrets.BACKEND_PROD_LOGDASH_API_KEY }}
          telegram-token: ${{ secrets.BACKEND_PROD_TELEGRAM_TOKEN }}
          whitelisted-emails: ${{ secrets.BACKEND_PROD_WHITELISTED_EMAILS }}
          auth-jwt-secret: ${{ secrets.BACKEND_PROD_AUTH_JWT_SECRET }}
      - name: Prune
        uses: './.github/templates/prune'
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
