name: Deploy backend (local)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'apps/backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/logdash-backend-local
      - name: Deploy
        uses: './.github/templates/deploy-container'
        with:
          host: ${{ secrets.BACKEND_LOCAL_SSH_HOST }}
          username: ${{ secrets.BACKEND_LOCAL_SSH_USER }}
          port: ${{ secrets.BACKEND_LOCAL_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_LOCAL_SSH_KEY }}
          server-port: 7001
          application-port: 3000
          image-name: ablaszkiewicz/logdash-backend-local
          container-name: logdash-backend-local
          mongo-url: ${{ secrets.BACKEND_DEV_MONGO_URL }}
          github-oauth-client-id: ${{ secrets.BACKEND_LOCAL_GITHUB_OAUTH_CLIENT_ID }}
          github-oauth-client-secret: ${{ secrets.BACKEND_LOCAL_GITHUB_OAUTH_CLIENT_SECRET }}
          resend-api-key: 'empty'
          resend-audience-enabled: 'false'
          stripe-api-key-secret: ${{ secrets.BACKEND_LOCAL_STRIPE_API_KEY_SECRET }}
          stripe-signature: ${{ secrets.BACKEND_LOCAL_STRIPE_SIGNATURE }}
          our-env: local
          redis-url: ${{ secrets.BACKEND_LOCAL_REDIS_URL }}
          stripe-early-bird-price-id: ${{ secrets.BACKEND_LOCAL_STRIPE_EARLY_BIRD_PRICE_ID }}
          demo-dashboard-api-key: ${{ secrets.BACKEND_LOCAL_DEMO_DASHBOARD_API_KEY }}
          logdash-api-key: ${{ secrets.BACKEND_LOCAL_LOGDASH_API_KEY }}
          telegram-token: ${{ secrets.BACKEND_LOCAL_TELEGRAM_TOKEN }}
          whitelisted-emails: ${{ secrets.BACKEND_LOCAL_WHITELISTED_EMAILS }}
          auth-jwt-secret: ${{ secrets.BACKEND_LOCAL_AUTH_JWT_SECRET }}
          clickhouse-host: ${{ secrets.BACKEND_LOCAL_CLICKHOUSE_HOST }}
          clickhouse-port: ${{ secrets.BACKEND_LOCAL_CLICKHOUSE_PORT }}
          clickhouse-user: ${{ secrets.BACKEND_LOCAL_CLICKHOUSE_USER }}
          clickhouse-password: ${{ secrets.BACKEND_LOCAL_CLICKHOUSE_PASSWORD }}
          clickhouse-db: default
          swagger-password: ${{ secrets.BACKEND_SWAGGER_PASSWORD }}
