name: Deploy backend (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'apps/backend/**'
      - '.github/workflows/**'

jobs:
  find-tests:
    runs-on: ubuntu-latest
    outputs:
      test-batches: ${{ steps.find-tests.outputs.test-batches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find test files
        id: find-tests
        uses: './.github/templates/find-tests'
        with:
          batch-size: '3'

  test:
    needs: find-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-batch: ${{ fromJson(needs.find-tests.outputs.test-batches) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test batch
        uses: './.github/templates/test'
        with:
          test-batch: ${{ matrix.test-batch }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/logdash-backend-dev
      - name: Deploy
        uses: './.github/templates/deploy-container'
        with:
          host: ${{ secrets.BACKEND_DEV_SSH_HOST }}
          username: ${{ secrets.BACKEND_DEV_SSH_USER }}
          port: ${{ secrets.BACKEND_DEV_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_DEV_SSH_KEY }}
          server-port: 3000
          application-port: 3000
          image-name: ablaszkiewicz/logdash-backend-dev
          container-name: logdash-backend-dev
          mongo-url: ${{ secrets.BACKEND_DEV_MONGO_URL }}
          github-oauth-client-id: ${{ secrets.BACKEND_DEV_GITHUB_OAUTH_CLIENT_ID }}
          github-oauth-client-secret: ${{ secrets.BACKEND_DEV_GITHUB_OAUTH_CLIENT_SECRET }}
          github-oauth-client-id-alternative: ${{ secrets.BACKEND_DEV_GITHUB_OAUTH_CLIENT_ID_ALTERNATIVE }}
          github-oauth-client-secret-alternative: ${{ secrets.BACKEND_DEV_GITHUB_OAUTH_CLIENT_SECRET_ALTERNATIVE }}
          resend-api-key: ${{ secrets.BACKEND_DEV_RESEND_API_KEY }}
          resend-audience-enabled: 'false'
          stripe-api-key-secret: ${{ secrets.BACKEND_DEV_STRIPE_API_KEY_SECRET }}
          stripe-signature: ${{ secrets.BACKEND_DEV_STRIPE_SIGNATURE }}
          our-env: dev
          redis-url: ${{ secrets.BACKEND_DEV_REDIS_URL }}
          stripe-early-bird-price-id: ${{ secrets.BACKEND_DEV_STRIPE_EARLY_BIRD_PRICE_ID }}
          stripe-builder-price-id: ${{ secrets.BACKEND_DEV_STRIPE_BUILDER_PRICE_ID }}
          stripe-pro-price-id: ${{ secrets.BACKEND_DEV_STRIPE_PRO_PRICE_ID }}
          demo-dashboard-api-key: ${{ secrets.BACKEND_DEV_DEMO_DASHBOARD_API_KEY }}
          logdash-api-key: ${{ secrets.BACKEND_DEV_LOGDASH_API_KEY }}
          telegram-token: ${{ secrets.BACKEND_DEV_TELEGRAM_TOKEN }}
          whitelisted-emails: ${{ secrets.BACKEND_DEV_WHITELISTED_EMAILS }}
          auth-jwt-secret: ${{ secrets.BACKEND_DEV_AUTH_JWT_SECRET }}
          clickhouse-host: ${{ secrets.BACKEND_DEV_CLICKHOUSE_HOST }}:${{ secrets.BACKEND_DEV_CLICKHOUSE_PORT }}
          clickhouse-user: ${{ secrets.BACKEND_DEV_CLICKHOUSE_USER }}
          clickhouse-password: ${{ secrets.BACKEND_DEV_CLICKHOUSE_PASSWORD }}
          clickhouse-database: default
          swagger-password: ${{ secrets.BACKEND_SWAGGER_PASSWORD }}
          telegram-uptime-bot-token: ${{ secrets.BACKEND_DEV_TELEGRAM_UPTIME_BOT_TOKEN }}
          telegram-uptime-bot-secret: ${{ secrets.BACKEND_DEV_TELEGRAM_UPTIME_BOT_SECRET }}
          admin-super-secret-admin-key: ${{ secrets.BACKEND_DEV_ADMIN_SUPER_SECRET_ADMIN_KEY }}
          internal-telegram-bot-token: ${{ secrets.BACKEND_DEV_INTERNAL_TELEGRAM_BOT_TOKEN }}
      - name: Prune
        uses: './.github/templates/prune'
        with:
          host: ${{ secrets.BACKEND_DEV_SSH_HOST }}
          username: ${{ secrets.BACKEND_DEV_SSH_USER }}
          port: ${{ secrets.BACKEND_DEV_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_DEV_SSH_KEY }}
