name: Deploy status-page (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'apps/status-page/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          context: ./
          file: ./apps/status-page/Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/logdash-status-page-dev
      - name: Deploy
        uses: './.github/templates/deploy-container'
        with:
          host: ${{ secrets.BACKEND_DEV_SSH_HOST }}
          username: ${{ secrets.BACKEND_DEV_SSH_USER }}
          port: ${{ secrets.BACKEND_DEV_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_DEV_SSH_KEY }}
          server-port: 4000
          application-port: 3000
          image-name: ablaszkiewicz/logdash-status-page-dev
          container-name: logdash-status-page-dev
      - name: Prune
        uses: './.github/templates/prune'
        with:
          host: ${{ secrets.BACKEND_DEV_SSH_HOST }}
          username: ${{ secrets.BACKEND_DEV_SSH_USER }}
          port: ${{ secrets.BACKEND_DEV_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_DEV_SSH_KEY }}
