name: Deploy status-page (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/status-page/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/status-page-build-and-push'
        with:
          context: ./
          file: ./apps/status-page/Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/logdash-status-page-prod
          build-args: |
            VITE_API_BASE_URL=https://api.logdash.io
      - name: Deploy
        uses: './.github/templates/deploy-status-page-container'
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
          server-port: 4000
          application-port: 3000
          image-name: ablaszkiewicz/logdash-status-page-prod
          container-name: logdash-status-page-prod
      - name: Prune
        uses: './.github/templates/prune'
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
